#!/usr/bin/env python3
"""The enemy-pointer arrow: one drawn PNG -> four directions -> src/arrows.s.

    python tools/arrowgen.py

The source is assets/png/enemy_arrow_right.png, 16x16, drawn with its tip at the
TOP of the image. It is NOT converted with --tate: the hardware's sprite axes are
the framebuffer's, fb-x runs DOWN the player's screen and fb-y runs LEFT, so the
top of an unrotated image is the player's RIGHT. The other three are that same
image turned, and saved beside it in the same (hardware) orientation:

    right   as drawn            tip toward fb-y 0
    left    turned 180          tip toward fb-y 299
    up      turned 90 ccw       tip toward fb-x 0
    down    turned 90 cw        tip toward fb-x 399

Each sprite is cropped to the rows it uses (the width stays 16, a valid bucket),
and the generated file carries the TIP's position inside it, so cam.s can put
the tip on the screen edge instead of guessing at a corner. All four share one
256-byte GPU page. Edit the right-pointing PNG and re-run; the other three PNGs
are outputs.
"""

import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sprgen import load_planes  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PNG = ROOT / "assets" / "png"
SRC = PNG / "enemy_arrow_right.png"
DST = ROOT / "src" / "arrows.s"

# Slot order is cam.s's ARW_RIGHT..ARW_DOWN.
DIRS = [
    ("right", None),
    ("left", Image.Transpose.ROTATE_180),
    ("up", Image.Transpose.ROTATE_90),
    ("down", Image.Transpose.ROTATE_270),
]


def tip(im, name):
    """The middle of the outermost opaque pixels on the side it points to."""
    w, h = im.size
    px = im.load()
    pts = [(x, y) for y in range(h) for x in range(w) if px[x, y][3] >= 128]
    if name in ("right", "left"):
        edge = min(y for _, y in pts) if name == "right" else max(y for _, y in pts)
        xs = [x for x, y in pts if y == edge]
        return (min(xs) + max(xs)) // 2, edge
    edge = min(x for x, _ in pts) if name == "up" else max(x for x, _ in pts)
    ys = [y for x, y in pts if x == edge]
    return edge, (min(ys) + max(ys)) // 2


def main():
    base = Image.open(SRC).convert("RGBA")
    if base.size != (16, 16):
        sys.exit(f"{SRC}: want 16x16, got {base.size}")

    out = [
        "; " + "=" * 75,
        "; arrows - GENERATED by tools/arrowgen.py from",
        f"; assets/png/{SRC.name}. Do not edit.",
        "; " + "=" * 75,
        "; The enemy-pointer arrow in four directions, one GPU page. NOT --tate:",
        "; the art is stored in the hardware's own axes (fb-x down the player's",
        "; screen, fb-y left), which is how the source PNG was drawn. TX/TY is the",
        "; tip's pixel inside the sprite - column (fb-x) and row (fb-y).",
        "; " + "=" * 75,
        "",
    ]
    blob = bytearray()
    for name, op in DIRS:
        im = base if op is None else base.transpose(op)
        if op is not None:
            im.save(PNG / f"enemy_arrow_{name}.png")
        rows = [y for y in range(16) if any(im.getpixel((x, y))[3] >= 128 for x in range(16))]
        im = im.crop((0, rows[0], 16, rows[-1] + 1))
        w, h, type_byte, data, has_overlay, _ = load_planes(im, False)
        tx, ty = tip(im, name)
        lbl = f"ARW_{name.upper()}"
        out += [
            f"; {name}: {w}x{h}, {'overlay' if has_overlay else 'NO overlay'}, "
            f"{len(data)} bytes, offset {len(blob)}, tip ({tx},{ty})",
            f"{lbl}_TYPE   = ${type_byte:02X}",
            f"{lbl}_HEIGHT = {h}",
            f"{lbl}_OFFSET = {len(blob)}",
            f"{lbl}_TX     = {tx}",
            f"{lbl}_TY     = {ty}",
        ]
        blob += data
        print(f"{name:5s}: {w}x{h} type ${type_byte:02X} {len(data)} B, tip ({tx},{ty})")
    if len(blob) > 256:
        sys.exit(f"{len(blob)} bytes - more than the one GPU page cam.s loads")
    out += ["", f"ARROWS_BYTES = {len(blob)}", "", "arrows_data:"]
    for i in range(0, len(blob), 16):
        out.append("        .byte   " + ", ".join(f"${b:02X}" for b in blob[i:i + 16]))
    out.append("")
    DST.write_text("\n".join(out))
    print(f"{len(blob)} bytes -> {DST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
