#!/usr/bin/env python3
"""The ejected capsule's sprite: the drawn PNGs of its animation -> src/capsule_art.s.

    python tools/capsulegen.py [SET]

SET names the frames: assets/png/<SET>1.png, <SET>2.png, ... as far as they go.
`capsule` (four 16x24 frames) is the default and, for now, the only set.

Modelled on tools/pickupgen.py - see that file for the shared conventions (the
overlay PNG format, the width-bucket rule). The one difference: the capsule is
its own sprite, not a shared "whatever the pickup holds" blob, so this writes
CAP_* constants and a capsule_data label instead of PK_*/pickups_data.

They are NOT converted with --tate: drawn in the hardware's own axes, exactly
like the pickup and the enemy arrow, so art drawn to read correctly on a TATE
screen is stored exactly as drawn.
"""

import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sprgen import load_planes  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PNG = ROOT / "assets" / "png"
DST = ROOT / "src" / "capsule_art.s"
MAX_PAGES = 2                           # the GPU pages capsule.s claims, $14-$15


def main(stem):
    names = []
    while (PNG / f"{stem}{len(names) + 1}.png").exists():
        names.append(f"{stem}{len(names) + 1}")
    if not names:
        sys.exit(f"no frames: {PNG / (stem + '1.png')} does not exist")
    out = [
        "; " + "=" * 75,
        "; capsule_art - GENERATED by tools/capsulegen.py from assets/png/",
        f"; {names[0]}.png .. {names[-1]}.png. Do not edit.",
        "; " + "=" * 75,
        f"; The ejected capsule: {len(names)} frames, in the hardware's own axes",
        "; (NOT --tate).",
        "; " + "=" * 75,
        "",
    ]
    blob = bytearray()
    first = None
    for name in names:
        src = PNG / f"{name}.png"
        im = Image.open(src).convert("RGBA")
        w, h, type_byte, data, has_overlay, _ = load_planes(im, False)
        if first is None:
            first = (w, h, type_byte, len(data))
        elif (w, h, type_byte, len(data)) != first:
            sys.exit(f"{src}: every frame must share one size and type")
        out.append(f"; {name}: {w}x{h}, {'overlay' if has_overlay else 'NO overlay'}, "
                   f"{len(data)} bytes, offset {len(blob)}")
        blob += data
        print(f"{name:10s}: {w}x{h} type ${type_byte:02X} {len(data)} B")
    pages = (len(blob) + 255) // 256
    if pages > MAX_PAGES:
        sys.exit(f"{len(blob)} bytes - more than the {MAX_PAGES} GPU pages capsule.s claims")
    blob += bytes(pages * 256 - len(blob))          # whole pages: LOAD takes 256
    w, h, type_byte, size = first
    out += [
        f"CAP_TYPE    = ${type_byte:02X}",
        f"CAP_W       = {w}             ; full-res px, along fb-x",
        f"CAP_HEIGHT  = {h}             ; ...and rows, along fb-y",
        f"CAP_FRAMES  = {len(names)}             ; the animation, one sprite slot each",
        f"CAP_BYTES   = {size}             ; ...frame n at n * this from CAP_PAGE",
        f"CAP_PAGES   = {pages}             ; GPU pages, from CAP_PAGE on",
        "",
        "capsule_data:",
    ]
    for i in range(0, len(blob), 16):
        out.append("        .byte   " + ", ".join(f"${b:02X}" for b in blob[i:i + 16]))
    out.append("")
    DST.write_text("\n".join(out))
    print(f"{len(blob)} bytes, {len(names)} frame(s), {pages} page(s) -> "
          f"{DST.relative_to(ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "capsule")
