# -----------------------------------------------------------------------------
# mkspeech.py - WHAT THE GAME SAYS, and the only place it is written
# -----------------------------------------------------------------------------
# `python tools/mkspeech.py` emits src/speech.inc: one phoneme string per spoken
# message plus SPK_LO/SPK_HI, the pointer table indexed by the IM_* id. The .inc
# is regenerated by `make` and tracked, so a diff of it is a diff of the voice -
# but EDIT THIS FILE, never the .inc.
#
# WHY A GENERATOR AT ALL. The bytes are %SSPPPPPP - a phoneme index in the low
# six bits, length and stress in the top two - and the table below is the English
# beside them. Hand-written .byte lines would be the same information with the
# English in a comment that nothing keeps honest.
#
# THE ORDER IS THE ABI. MESSAGES has one entry per IM_* id, IN ID ORDER
# (hud_game.s), because SPK_LO/SPK_HI are indexed by that id exactly as
# IND_LO/IND_HI are. A message with no phonemes is SILENT and gets a $00 pointer:
# the bar shows it and nothing is said. src/speech.s asserts the count against
# IM_COUNT, so adding an id without coming here is a build error, not a mystery.
#
# WRITING AN UTTERANCE. One tuple per phoneme: (phoneme, stress, comment).
#
#   * A DIPHTHONG IS TWO VOWELS. /eI/ (gATE) is EH then I, /aI/ (acquIred) is AA
#     then I, /oU/ (OPen) is AO then UH.
#   * EVERY STOP IS A CLOSURE AND THEN A BURST: CLS before P/T/K, CLZ before
#     B/D/G. Leave the silence out and /t/ is a click, not a T. The formants keep
#     gliding through the closure, so the burst already sits at the locus of the
#     vowel behind it - which is most of what tells /d/ from /k/.
#   * PAU is the gap between words, and it is not optional: without it
#     "LASER ACQUIRED" is one word.
#   * X (SHORT) is for an unstressed syllable, S (STRESS) for the one the word
#     leans on, L (LONG) for a final consonant that would otherwise clip.
#
# THE TEXT MUST BE WHAT IS ON SCREEN. Speech reduced to three squares is
# recognisable, not decodable cold: the prototype was accepted on the condition
# that the words are displayed while they are spoken (MAD-65 carts/speech_test).
# The `text` field here is the message as hud_game.s / shield.s / gate.s /
# pickup.s display it. Nothing checks that copy - so when a message's wording
# changes, its phonemes change in the same commit.
# -----------------------------------------------------------------------------
import os

N, S, L, X = "SPK_NORM", "SPK_STRESS", "SPK_LONG", "SPK_SHORT"

SPK_BUF_LEN = 64                 # the OS's buffer: 63 phonemes + terminator

# (IM_* id name, the text on the bar, phonemes or None for a silent message)
MESSAGES = [
    ("IM_HULL",       "HULL BREACH",       None),
    # The "!" is written, never spoken - the voice leans on WARNING instead, which
    # is what an exclamation mark is for. This is the one line a player has to act
    # on within seconds, so it is the one where the words on screen are least likely
    # to be read in time: the reason for a voice at all.
    ("IM_CRITICAL",   "WARNING! HULL CRITICAL", [
        ("W",   N, "WARNING   /wO-nIng/"),
        ("AO",  S, ""),
        ("R",   N, ""),
        ("N",   N, ""),
        ("IH",  X, ""),
        ("NG",  L, ""),
        ("PAU", N, ""),
        ("HH",  N, "HULL"),
        ("AH",  S, ""),
        ("L",   N, ""),
        ("PAU", N, ""),
        ("CLS", N, "CRITICAL   /krI-tI-k@l/"),
        ("K",   N, ""),
        ("R",   N, ""),
        ("IH",  S, ""),
        ("CLS", N, ""),
        ("T",   N, ""),
        ("IH",  X, ""),
        ("CLS", N, ""),
        ("K",   N, ""),
        ("AX",  X, ""),
        ("L",   L, ""),
    ]),
    ("IM_LEVEL",      "CLEAR THE SECTOR",  None),
    ("IM_LIFE",       "SHIP LOST", [
        ("SH",  N, "SHIP"),
        ("IH",  S, ""),
        ("CLS", N, ""),
        ("P",   N, ""),
        ("PAU", N, ""),
        ("L",   N, "LOST"),
        ("AO",  S, ""),
        ("S",   N, ""),
        ("CLS", N, ""),
        ("T",   L, ""),
    ]),
    ("IM_ENEMY",      "ENEMY DETECTED",    None),
    ("IM_GUN",        "BLASTER ARMED",     None),
    ("IM_LASER",      "LASER ARMED",       None),
    ("IM_EMP_NA",     "EMP NOT AVAILABLE", None),

    ("IM_SHIELD_ON",  "SHIELD ENABLED", [
        ("SH",  N, "SHIELD"),
        ("I",   S, ""),
        ("L",   N, ""),
        ("CLZ", N, ""),
        ("D",   N, ""),
        ("PAU", N, ""),
        ("IH",  X, "ENABLED   /I-neI-bld/"),
        ("N",   N, ""),
        ("EH",  S, "  /eI/"),
        ("I",   N, ""),
        ("CLZ", N, ""),
        ("B",   N, ""),
        ("AX",  X, ""),
        ("L",   N, ""),
        ("CLZ", N, ""),
        ("D",   N, ""),
    ]),

    ("IM_SHIELD_OFF", "SHIELD OFF", [
        ("SH",  N, "SHIELD"),
        ("I",   S, ""),
        ("L",   N, ""),
        ("CLZ", N, ""),
        ("D",   N, ""),
        ("PAU", N, ""),
        ("AO",  S, "OFF"),
        ("F",   L, ""),
    ]),

    ("IM_GATE",       "EXIT GATE OPEN", [
        ("EH",  S, "EXIT   /EK-sIt/"),
        ("CLS", N, ""),
        ("K",   N, ""),
        ("S",   N, ""),
        ("IH",  X, ""),
        ("CLS", N, ""),
        ("T",   N, ""),
        ("PAU", N, ""),
        ("CLZ", N, "GATE"),
        ("G",   N, ""),
        ("EH",  S, "  /eI/"),
        ("I",   N, ""),
        ("CLS", N, ""),
        ("T",   N, ""),
        ("PAU", N, ""),
        ("AO",  S, "OPEN   /oU-p@n/"),
        ("UH",  N, "  /oU/"),
        ("CLS", N, ""),
        ("P",   N, ""),
        ("AX",  X, ""),
        ("N",   L, ""),
    ]),

    ("IM_LASER_GOT",  "LASER ACQUIRED", [
        ("L",   N, "LASER"),
        ("EH",  S, "  /eI/"),
        ("I",   N, ""),
        ("Z",   N, ""),
        ("ER",  N, ""),
        ("PAU", N, ""),
        ("AX",  X, "ACQUIRED   /@-kwaI-@d/"),
        ("CLS", N, ""),
        ("K",   N, ""),
        ("W",   N, ""),
        ("AA",  S, "  /aI/"),
        ("I",   N, ""),
        ("ER",  N, ""),
        ("CLZ", N, ""),
        ("D",   N, ""),
    ]),

    # EMP is SPELT OUT and each letter is HELD - EEE, EM, PEE - not sounded as a
    # word. It is the one message whose voice does not read the letters on the bar
    # straight through, and the reason is that "emp" as a syllable is not a word
    # anybody hears as a weapon. The letters are doubled (I+I, and the nasal of EM
    # LONG) because a single vowel at this tempo reads as a clipped E, not a name.
    ("IM_EMP_GOT",    "EMP ACQUIRED", [
        ("I",   S, "E - the letter, held: EEE"),
        ("I",   L, ""),
        ("PAU", N, ""),
        ("EH",  S, "M - EM, on the nasal"),
        ("M",   L, ""),
        ("PAU", N, ""),
        ("CLS", N, "P - PEE"),
        ("P",   N, ""),
        ("I",   S, ""),
        ("I",   L, ""),
        ("PAU", N, ""),
        ("AX",  X, "ACQUIRED   /@-kwaI-@d/"),
        ("CLS", N, ""),
        ("K",   N, ""),
        ("W",   N, ""),
        ("AA",  S, "  /aI/"),
        ("I",   N, ""),
        ("ER",  N, ""),
        ("CLZ", N, ""),
        ("D",   N, ""),
    ]),

    # The other half of the EMP's readout: the ring flashes at SATN_FULL, this
    # says it in words. It only speaks when the weapon is already in hand - a
    # full hold with no EMP found has nothing to announce (emp.s emp_ready).
    ("IM_EMP_RDY",    "EMP AVAILABLE", [
        ("I",   S, "E - the letter, held: EEE"),
        ("I",   L, ""),
        ("PAU", N, ""),
        ("EH",  S, "M - EM, on the nasal"),
        ("M",   L, ""),
        ("PAU", N, ""),
        ("CLS", N, "P - PEE"),
        ("P",   N, ""),
        ("I",   S, ""),
        ("I",   L, ""),
        ("PAU", N, ""),
        ("AX",  X, "AVAILABLE   /@-veI-l@-bl/"),
        ("V",   N, ""),
        ("EH",  S, "  /eI/"),
        ("I",   N, ""),
        ("L",   N, ""),
        ("AX",  X, ""),
        ("CLZ", N, ""),
        ("B",   N, ""),
        ("AX",  X, ""),
        ("L",   L, ""),
    ]),
    ("IM_GOAL1",      "BREAK BIGGEST ROCKS", None),
    ("IM_GOAL2",      "DEFEAT ALL ENEMIES",  None),
]


# THE ENDING of the demo (gate.s sector_frame): the SECTOR COMPLETED screen is not
# the flight, so it has no IM_* id and no message bar. Its lines are spoken one by
# one and each is put on the screen as its voice starts; the screen waits for
# SPK_BUSY to clear before the next, and only after the last does it listen for
# FIRE. ENDING is in line order, and the text (UICODE, gate.s end_s*) must match.
ENDING = [
    ("SECTOR CLEARED", [
        ("S",   N, "SECTOR   /sEk-t@r/"),
        ("EH",  S, ""),
        ("CLS", N, ""),
        ("K",   N, ""),
        ("CLS", N, ""),
        ("T",   N, ""),
        ("ER",  N, ""),
        ("PAU", N, ""),
        ("CLS", N, "CLEARED   /klI@d/"),
        ("K",   N, ""),
        ("L",   N, ""),
        ("I",   S, ""),
        ("ER",  N, ""),
        ("CLZ", N, ""),
        ("D",   N, ""),
    ]),
    ("THANK YOU FOR PLAYING", [
        ("TH",  N, "THANK"),
        ("AE",  S, ""),
        ("NG",  N, ""),
        ("CLS", N, ""),
        ("K",   N, ""),
        ("PAU", N, ""),
        ("Y",   N, "YOU"),
        ("UW",  S, ""),
        ("UW",  N, ""),
        ("PAU", N, ""),
        ("F",   N, "FOR"),
        ("AO",  S, ""),
        ("R",   N, ""),
        ("PAU", N, ""),
        ("CLS", N, "PLAYING"),
        ("P",   N, ""),
        ("L",   N, ""),
        ("EH",  S, ""),
        ("I",   N, ""),
        ("IH",  X, ""),
        ("NG",  L, ""),
    ]),
    ("ESCAPE FROM SATURN ALPHA", [
        ("IH",  X, "ESCAPE   /Is-keIp/"),
        ("S",   N, ""),
        ("CLS", N, ""),
        ("K",   N, ""),
        ("EH",  S, "  /eI/"),
        ("I",   N, ""),
        ("CLS", N, ""),
        ("P",   N, ""),
        ("PAU", N, ""),
        ("F",   N, "FROM"),
        ("R",   N, ""),
        ("AH",  S, ""),
        ("M",   N, ""),
        ("PAU", N, ""),
        ("S",   N, "SATURN"),
        ("AE",  S, ""),
        ("CLS", N, ""),
        ("T",   N, ""),
        ("ER",  N, ""),
        ("N",   N, ""),
        ("PAU", N, ""),
        ("AE",  S, "ALPHA"),
        ("L",   N, ""),
        ("F",   N, ""),
        ("AX",  L, ""),
    ]),
]


def emit(path):
    out = ["; Generated by tools/mkspeech.py - DO NOT EDIT. Edit MESSAGES there.",
           ";",
           "; One phoneme per byte, %SSPPPPPP: the OS's phoneme index in the low six",
           "; bits, the length and stress in the top two; a low six bits of zero ends",
           "; the string. Read straight out of the message bank by spk_say, which",
           "; copies it - see src/speech.s.",
           ""]
    spoken = 0
    phbytes = 0
    for idx, (name, text, u) in enumerate(MESSAGES):
        if u is None:
            continue
        assert len(u) < SPK_BUF_LEN, \
            "%s is %d phonemes; the OS buffer holds %d" \
            % (name, len(u), SPK_BUF_LEN - 1)
        spoken += 1
        phbytes += len(u) + 1
        out.append('; %s (id %d) - "%s": %d phonemes, roughly %d frames'
                   % (name, idx, text, len(u), 4 * len(u)))
        out.append("%s_PH:" % name)
        for ph, ss, cm in u:
            line = "        .byte   %-11s| SPK_PH_%-4s" % (ss, ph)
            out.append(line.rstrip() + ("   ; " + cm if cm else ""))
        out.append("        .byte   $00")
        out.append("")

    out.append("; The pointer table: one entry per IM_* id, IN ID ORDER, $00 where the")
    out.append("; message is not spoken. Read INSIDE the message bank's window (speech.s).")
    for half, tab in (("<", "LO"), (">", "HI")):
        out.append("SPK_%s:" % tab)
        for idx, (name, text, u) in enumerate(MESSAGES):
            ref = ("%s%s_PH" % (half, name)) if u else "$00"
            out.append("        .byte   %-16s; %2d %s" % (ref, idx, text))
    out.append("")
    out.append("SPK_IDS     = %d                 ; ...and how many, for speech.s's assert"
               % len(MESSAGES))
    out.append("")
    out.append("; The ending's lines (ENDING in mkspeech.py), spoken by gate.s sector_frame.")
    for i, (text, u) in enumerate(ENDING):
        assert len(u) < SPK_BUF_LEN, "ENDING %d is too long" % i
        out.append('; "%s": %d phonemes' % (text, len(u)))
        out.append("SPK_END%d_PH:" % i)
        for ph, ss, cm in u:
            line = "        .byte   %-11s| SPK_PH_%-4s" % (ss, ph)
            out.append(line.rstrip() + ("   ; " + cm if cm else ""))
        out.append("        .byte   $00")
    for half, tab in (("<", "LO"), (">", "HI")):
        out.append("SPK_END_%s:" % tab)
        for i, (text, u) in enumerate(ENDING):
            out.append("        .byte   %s%s" % (half, "SPK_END%d_PH" % i))
    out.append("SPK_END_N   = %d" % len(ENDING))
    with open(path, "w", newline="\r\n") as f:
        f.write("\n".join(out) + "\n")
    return spoken, phbytes


if __name__ == '__main__':
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    spoken, phbytes = emit(os.path.join(root, 'src', 'speech.inc'))
    for name, text, u in MESSAGES:
        if u:
            print('  %-14s "%s" - %d phonemes' % (name, text, len(u)))
    print('src/speech.inc written: %d of %d messages speak, %d bytes of phonemes '
          'and %d of pointers' % (spoken, len(MESSAGES), phbytes, 2 * len(MESSAGES)))
