#!/usr/bin/env python3
"""The pickup's sprite: two drawn PNGs -> src/pickups_art.s.

    python tools/pickupgen.py [SET]

SET names the pair: assets/png/<SET>1.png and <SET>2.png, the two animation
frames of ONE sprite every pickup shares, the laser and the shield alike.
`bonusmid` (32x32) is the default; the Makefile's PICKUP_SET picks. Both
frames must share one size, a valid width bucket (8/16/32/64). They are NOT converted with --tate: like the enemy arrow
(arrowgen.py) they are drawn in the hardware's own axes - fb-x down the
player's screen, fb-y left - so they are stored as drawn.

The frames are packed back to back from the start of PK_PAGE and may cross
into the next page (a 32x32 overlay frame is a whole page); PK_PAGES says how
many GPU pages pickup.s loads, and PK_OFF0/PK_OFF1 where each frame starts.
"""

import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sprgen import load_planes  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PNG = ROOT / "assets" / "png"
DST = ROOT / "src" / "pickups_art.s"
MAX_PAGES = 2                           # pickup.s's GPU pages, $13-$14


def main(stem):
    names = [f"{stem}1", f"{stem}2"]
    out = [
        "; " + "=" * 75,
        "; pickups_art - GENERATED by tools/pickupgen.py from assets/png/",
        f"; {names[0]}.png and {names[1]}.png. Do not edit.",
        "; " + "=" * 75,
        "; The pickup: two frames, in the hardware's own axes (NOT --tate).",
        "; Every pickup, whatever it holds, looks like this.",
        "; " + "=" * 75,
        "",
    ]
    blob = bytearray()
    first = None
    offs = []
    for name in names:
        src = PNG / f"{name}.png"
        im = Image.open(src).convert("RGBA")
        w, h, type_byte, data, has_overlay, _ = load_planes(im, False)
        if first is None:
            first = (w, h, type_byte, len(data))
        elif (w, h, type_byte, len(data)) != first:
            sys.exit(f"{src}: both frames must share one size and type")
        out.append(f"; {name}: {w}x{h}, {'overlay' if has_overlay else 'NO overlay'}, "
                   f"{len(data)} bytes, offset {len(blob)}")
        offs.append(len(blob))
        blob += data
        print(f"{name:10s}: {w}x{h} type ${type_byte:02X} {len(data)} B")
    pages = (len(blob) + 255) // 256
    if pages > MAX_PAGES:
        sys.exit(f"{len(blob)} bytes - more than the {MAX_PAGES} GPU pages pickup.s loads")
    blob += bytes(pages * 256 - len(blob))          # whole pages: LOAD takes 256
    w, h, type_byte, _ = first
    out += [
        f"PK_TYPE     = ${type_byte:02X}",
        f"PK_W        = {w}             ; full-res px, along fb-x",
        f"PK_HEIGHT   = {h}             ; ...and rows, along fb-y",
        f"PK_OFF0     = {offs[0]}             ; each frame's byte offset from PK_PAGE",
        f"PK_OFF1     = {offs[1]}",
        f"PK_PAGES    = {pages}             ; GPU pages loaded, from PK_PAGE on",
        "",
        "pickups_data:",
    ]
    for i in range(0, len(blob), 16):
        out.append("        .byte   " + ", ".join(f"${b:02X}" for b in blob[i:i + 16]))
    out.append("")
    DST.write_text("\n".join(out))
    print(f"{len(blob)} bytes, {pages} page(s) -> {DST.relative_to(ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "bonusmid")
