#!/usr/bin/env python3
"""PNG -> MAD-65 sprite blob, as an assembler source file.

    python tools/sprgen.py assets/png/ship32.png src/ship32.s ship32 --tate

`--tate` pre-rotates the art for a monitor on its side: a sprite's width axis
runs DOWN the player's screen and its height axis runs LEFT, so art drawn
upright has to be stored turned counter-clockwise. That is the whole TATE
convention - the hardware does nothing at runtime, the asset is simply rotated.

The PNG convention is CETAS's, and the two planes are what the hardware wants:

    transparent      -> both planes 0, "leave the screen alone"
    white, opaque    -> BITMAP bit, OR-ed onto the screen (the white silhouette)
    anything else    -> OVERLAY bit, AND-NOT-ed (black detail punched on top)

The composite the GPU performs is `screen = (screen OR bitmap) AND NOT overlay`,
so a sprite with no opaque-black pixels needs no overlay plane at all and can be
declared with the cheaper no-overlay type - the script says so when that is the
case, since dropping the plane halves both the data and the blit.

Row layout, from MAD65_GPU_OS.md: an overlay sprite stores each row as W bitmap
bytes followed by W overlay bytes, MSB = leftmost, W = width/8.

BATCH MODE packs several small sprites (e.g. an animation set) into one shared
256-byte GPU page, back to back, so the whole set costs one LOAD:

    python tools/sprgen.py --batch src/flames.s flames --tate \\
        flame_large_up1=assets/png/flame_large_up1.png \\
        flame_large_up2=assets/png/flame_large_up2.png ...

Each sprite still gets its own TYPE/HEIGHT/OFFSET constants (OFFSET is the byte
offset into the shared blob, for SPR_PTR_LSB); width is padded with transparent
columns up to the next encodable bucket (8/16/32/64) if the source - or the
source after --tate - is narrower than 8px, since the hardware has no bucket
below that.
"""

import sys

from PIL import Image

WIDTH_BUCKETS = (8, 16, 32, 64)


def load_planes(im, tate):
    if tate:
        # TATE: the monitor is on its side, so a sprite's WIDTH axis runs DOWN
        # the player's screen and its HEIGHT axis runs LEFT. Art drawn upright in
        # the PNG therefore lands rotated 90 degrees unless it is pre-rotated -
        # which is the whole TATE convention: no runtime transform anywhere, the
        # asset is simply stored turned. "Up" has to become "left", so this turns
        # the image counter-clockwise.
        im = im.rotate(90, expand=True)
    w, h = im.size

    if w not in WIDTH_BUCKETS:
        # pad transparent columns, centered, up to the next valid width bucket -
        # the hardware only encodes 8/16/32/64 in the type nibble, so a source
        # (or a --tate rotation of one) at any other width - even a multiple of
        # 8, like 24 - has no bucket of its own.
        target = next((b for b in WIDTH_BUCKETS if b >= w), None)
        if target is None:
            sys.exit(f"width {w} cannot be padded up to an encodable bucket")
        padded = Image.new("RGBA", (target, h), (0, 0, 0, 0))
        padded.paste(im, ((target - w) // 2, 0))
        im = padded
        w = target
    if w not in WIDTH_BUCKETS:
        sys.exit(f"width {w} cannot be encoded in a type byte (8/16/32/64 only)")
    if not 1 <= h <= 255:
        sys.exit(f"height {h} out of range")
    px = im.load()

    wb = w // 8
    bitmap, overlay = [], []
    for y in range(h):
        brow = bytearray(wb)
        orow = bytearray(wb)
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < 128:
                continue
            bit = 0x80 >> (x & 7)
            if (r, g, b) == (255, 255, 255):
                brow[x >> 3] |= bit
            else:
                orow[x >> 3] |= bit
        bitmap.append(bytes(brow))
        overlay.append(bytes(orow))

    has_overlay = any(any(r) for r in overlay)
    type_byte = {1: 0x01, 2: 0x02, 4: 0x04, 8: 0x08}[wb]
    if not has_overlay:
        type_byte |= 0x10

    data = bytearray()
    for y in range(h):
        data += bitmap[y]
        if has_overlay:
            data += overlay[y]

    return w, h, type_byte, bytes(data), has_overlay, overlay


def main(src, dst, label, tate=False):
    im = Image.open(src).convert("RGBA")
    w, h, type_byte, data, has_overlay, overlay = load_planes(im, tate)
    wb = w // 8

    out = [
        "; " + "=" * 75,
        f"; {label} - GENERATED by tools/sprgen.py from {src}. Do not edit.",
        "; " + "=" * 75,
        f"; {w} x {h}, {'overlay' if has_overlay else 'NO overlay'}, "
        f"type ${type_byte:02X}, {len(data)} bytes"
        f"{' (exactly one LOAD page)' if len(data) == 256 else ''}.",
        ";",
        "; Row layout: " + ("W bitmap bytes then W overlay bytes"
                            if has_overlay else "W bitmap bytes") +
        f", W = {wb}.",
        "; " + "=" * 75,
        "",
        f"{label.upper()}_TYPE   = ${type_byte:02X}",
        f"{label.upper()}_HEIGHT = {h}",
        f"{label.upper()}_BYTES  = {len(data)}",
        "",
        f"{label}_data:",
    ]
    stride = wb * (2 if has_overlay else 1)
    for y in range(h):
        row = data[y * stride:(y + 1) * stride]
        out.append("        .byte   " + ", ".join(f"${b:02X}" for b in row))
    out.append("")
    open(dst, "w").write("\n".join(out))

    print(f"{src}: {w}x{h}, overlay {'yes' if has_overlay else 'no'}, "
          f"type ${type_byte:02X}, {len(data)} bytes -> {dst}")
    if has_overlay:
        opaque_black = sum(bin(int.from_bytes(r, 'big')).count('1')
                           for r in overlay)
        print(f"  {opaque_black} overlay pixels. Drop them from the PNG and the "
              f"sprite halves to {len(data)//2} bytes with type "
              f"${type_byte | 0x10:02X}.")


def main_batch(dst, blob_label, entries, tate):
    """entries: list of (sprite_label, src_path). All packed into one blob,
    back to back, in the order given - so that order is also upload order and
    the offsets are stable across regeneration only if the entry list is."""
    offset = 0
    sprites = []   # (label, w, h, type_byte, data)
    for label, src in entries:
        im = Image.open(src).convert("RGBA")
        w, h, type_byte, data, has_overlay, overlay = load_planes(im, tate)
        if has_overlay:
            sys.exit(f"{src}: has overlay (black) pixels - batch mode assumes "
                      f"none, since flames are meant to be a single colour")
        sprites.append((label, src, w, h, type_byte, data, offset))
        offset += len(data)
    total = offset
    if total > 256:
        print(f"WARNING: blob is {total} bytes - spans more than one 256-byte "
              f"GPU page; the upload code must LOAD each page separately.",
              file=sys.stderr)

    out = [
        "; " + "=" * 75,
        f"; {blob_label} - GENERATED by tools/sprgen.py --batch. Do not edit.",
        "; " + "=" * 75,
        f"; {len(sprites)} sprites packed into one {total}-byte blob"
        f"{' (exactly one LOAD page)' if total == 256 else ''}.",
        "; All NO-overlay (pure white/transparent), width padded to 8px where",
        "; the source (or its --tate rotation) came out narrower.",
        "; " + "=" * 75,
        "",
    ]
    for label, src, w, h, type_byte, data, off in sprites:
        out.append(f"; {label} - from {src}: {w}x{h}, type ${type_byte:02X}, "
                    f"{len(data)} bytes, offset {off}")
        out.append(f"{label.upper()}_TYPE   = ${type_byte:02X}")
        out.append(f"{label.upper()}_HEIGHT = {h}")
        out.append(f"{label.upper()}_OFFSET = {off}")
    out.append("")
    out.append(f"{blob_label}_BYTES = {total}")
    out.append("")
    out.append(f"{blob_label}_data:")
    blob = b"".join(d for (_, _, _, _, _, d, _) in sprites)
    for i in range(0, len(blob), 16):
        row = blob[i:i + 16]
        out.append("        .byte   " + ", ".join(f"${b:02X}" for b in row))
    out.append("")
    open(dst, "w").write("\n".join(out))

    print(f"--batch: {len(sprites)} sprites, {total} bytes total -> {dst}")


if __name__ == "__main__":
    argv = sys.argv[1:]
    if argv and argv[0] == "--batch":
        rest = argv[1:]
        tate = "--tate" in rest
        rest = [a for a in rest if a != "--tate"]
        if len(rest) < 3:
            sys.exit(__doc__)
        dst, blob_label, *entry_args = rest
        entries = []
        for e in entry_args:
            if "=" not in e:
                sys.exit(f"bad entry {e!r}, want label=path.png")
            lbl, path = e.split("=", 1)
            entries.append((lbl, path))
        main_batch(dst, blob_label, entries, tate)
    else:
        args = [a for a in argv if a != "--tate"]
        if len(args) != 3:
            sys.exit(__doc__)
        main(*args, tate="--tate" in argv)
