#!/usr/bin/env python3
"""PNG -> MAD-65 sprite blob, as an assembler source file.

    python tools/sprgen.py assets/png/ship32.png proto/01_flight/ship32.s ship32 --tate

`--tate` pre-rotates the art for a monitor on its side: a sprite's width axis
runs DOWN the player's screen and its height axis runs LEFT, so art drawn
upright has to be stored turned counter-clockwise. That is the whole TATE
convention - the hardware does nothing at runtime, the asset is simply rotated.

The PNG convention is CETAS's, and the two planes are what the hardware wants:

    transparent      -> both planes 0, "leave the screen alone"
    white, opaque    -> BITMAP bit, OR-ed onto the screen (the white silhouette)
    anything else    -> OVERLAY bit, AND-NOT-ed (black detail punched on top)

The composite the GPU performs is `screen = (screen OR bitmap) AND NOT overlay`,
so a sprite with no opaque-black pixels needs no overlay plane at all and can be
declared with the cheaper no-overlay type - the script says so when that is the
case, since dropping the plane halves both the data and the blit.

Row layout, from MAD65_GPU_OS.md: an overlay sprite stores each row as W bitmap
bytes followed by W overlay bytes, MSB = leftmost, W = width/8.
"""

import sys

from PIL import Image


def main(src, dst, label, tate=False):
    im = Image.open(src).convert("RGBA")
    if tate:
        # TATE: the monitor is on its side, so a sprite's WIDTH axis runs DOWN
        # the player's screen and its HEIGHT axis runs LEFT. Art drawn upright in
        # the PNG therefore lands rotated 90 degrees unless it is pre-rotated -
        # which is the whole TATE convention: no runtime transform anywhere, the
        # asset is simply stored turned. "Up" has to become "left", so this turns
        # the image counter-clockwise.
        im = im.rotate(90, expand=True)
    w, h = im.size
    if w % 8:
        sys.exit(f"width {w} is not a multiple of 8")
    if w not in (8, 16, 32, 64):
        sys.exit(f"width {w} cannot be encoded in a type byte (8/16/32/64 only)")
    if not 1 <= h <= 255:
        sys.exit(f"height {h} out of range")
    px = im.load()

    wb = w // 8
    bitmap, overlay = [], []
    for y in range(h):
        brow = bytearray(wb)
        orow = bytearray(wb)
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < 128:
                continue
            bit = 0x80 >> (x & 7)
            if (r, g, b) == (255, 255, 255):
                brow[x >> 3] |= bit
            else:
                orow[x >> 3] |= bit
        bitmap.append(bytes(brow))
        overlay.append(bytes(orow))

    has_overlay = any(any(r) for r in overlay)
    type_byte = {1: 0x01, 2: 0x02, 4: 0x04, 8: 0x08}[wb]
    if not has_overlay:
        type_byte |= 0x10

    data = bytearray()
    for y in range(h):
        data += bitmap[y]
        if has_overlay:
            data += overlay[y]

    out = [
        "; " + "=" * 75,
        f"; {label} - GENERATED by tools/sprgen.py from {src}. Do not edit.",
        "; " + "=" * 75,
        f"; {w} x {h}, {'overlay' if has_overlay else 'NO overlay'}, "
        f"type ${type_byte:02X}, {len(data)} bytes"
        f"{' (exactly one LOAD page)' if len(data) == 256 else ''}.",
        ";",
        "; Row layout: " + ("W bitmap bytes then W overlay bytes"
                            if has_overlay else "W bitmap bytes") +
        f", W = {wb}.",
        "; " + "=" * 75,
        "",
        f"{label.upper()}_TYPE   = ${type_byte:02X}",
        f"{label.upper()}_HEIGHT = {h}",
        f"{label.upper()}_BYTES  = {len(data)}",
        "",
        f"{label}_data:",
    ]
    stride = wb * (2 if has_overlay else 1)
    for y in range(h):
        row = data[y * stride:(y + 1) * stride]
        out.append("        .byte   " + ", ".join(f"${b:02X}" for b in row))
    out.append("")
    open(dst, "w").write("\n".join(out))

    print(f"{src}: {w}x{h}, overlay {'yes' if has_overlay else 'no'}, "
          f"type ${type_byte:02X}, {len(data)} bytes -> {dst}")
    if has_overlay:
        opaque_black = sum(bin(int.from_bytes(r, 'big')).count('1')
                           for r in overlay)
        print(f"  {opaque_black} overlay pixels. Drop them from the PNG and the "
              f"sprite halves to {len(data)//2} bytes with type "
              f"${type_byte | 0x10:02X}.")


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if a != "--tate"]
    if len(args) != 3:
        sys.exit(__doc__)
    main(*args, tate="--tate" in sys.argv)
