; ===========================================================================
; arrows - GENERATED by tools/arrowgen.py from
; assets/png/enemy_arrow_right.png. Do not edit.
; ===========================================================================
; The enemy-pointer arrow in four directions, one GPU page. NOT --tate:
; the art is stored in the hardware's own axes (fb-x down the player's
; screen, fb-y left), which is how the source PNG was drawn. TX/TY is the
; tip's pixel inside the sprite - column (fb-x) and row (fb-y).
; ===========================================================================

; right: 16x11, overlay, 44 bytes, offset 0, tip (7,0)
ARW_RIGHT_TYPE   = $02
ARW_RIGHT_HEIGHT = 11
ARW_RIGHT_OFFSET = 0
ARW_RIGHT_TX     = 7
ARW_RIGHT_TY     = 0
; left: 16x11, overlay, 44 bytes, offset 44, tip (8,10)
ARW_LEFT_TYPE   = $02
ARW_LEFT_HEIGHT = 11
ARW_LEFT_OFFSET = 44
ARW_LEFT_TX     = 8
ARW_LEFT_TY     = 10
; up: 16x15, overlay, 60 bytes, offset 88, tip (0,7)
ARW_UP_TYPE   = $02
ARW_UP_HEIGHT = 15
ARW_UP_OFFSET = 88
ARW_UP_TX     = 0
ARW_UP_TY     = 7
; down: 16x15, overlay, 60 bytes, offset 148, tip (15,7)
ARW_DOWN_TYPE   = $02
ARW_DOWN_HEIGHT = 15
ARW_DOWN_OFFSET = 148
ARW_DOWN_TX     = 15
ARW_DOWN_TY     = 7

ARROWS_BYTES = 208

arrows_data:
        .byte   $00, $00, $03, $80, $01, $00, $06, $C0, $03, $80, $0C, $60, $06, $C0, $19, $30
        .byte   $0C, $60, $33, $98, $18, $30, $67, $CC, $30, $18, $CF, $E6, $60, $0C, $9F, $F2
        .byte   $78, $3C, $87, $C2, $1F, $F0, $E0, $0E, $00, $00, $FF, $FE, $00, $00, $7F, $FF
        .byte   $0F, $F8, $70, $07, $3C, $1E, $43, $E1, $30, $06, $4F, $F9, $18, $0C, $67, $F3
        .byte   $0C, $18, $33, $E6, $06, $30, $19, $CC, $03, $60, $0C, $98, $01, $C0, $06, $30
        .byte   $00, $80, $03, $60, $00, $00, $01, $C0, $00, $00, $03, $E0, $01, $80, $06, $60
        .byte   $03, $80, $0C, $60, $06, $C0, $19, $20, $0C, $C0, $33, $20, $18, $40, $67, $A0
        .byte   $30, $40, $CF, $A0, $60, $40, $9F, $A0, $30, $40, $CF, $A0, $18, $40, $67, $A0
        .byte   $0C, $C0, $33, $20, $06, $C0, $19, $20, $03, $80, $0C, $60, $01, $80, $06, $60
        .byte   $00, $00, $03, $E0, $00, $00, $07, $C0, $01, $80, $06, $60, $01, $C0, $06, $30
        .byte   $03, $60, $04, $98, $03, $30, $04, $CC, $02, $18, $05, $E6, $02, $0C, $05, $F3
        .byte   $02, $06, $05, $F9, $02, $0C, $05, $F3, $02, $18, $05, $E6, $03, $30, $04, $CC
        .byte   $03, $60, $04, $98, $01, $C0, $06, $30, $01, $80, $06, $60, $00, $00, $07, $C0
