; ===========================================================================
; arrows - GENERATED by tools/arrowgen.py from
; assets/png/enemy_arrow_right.png. Do not edit.
; ===========================================================================
; The enemy-pointer arrow in four directions, one GPU page. NOT --tate:
; the art is stored in the hardware's own axes (fb-x down the player's
; screen, fb-y left), which is how the source PNG was drawn. TX/TY is the
; tip's pixel inside the sprite - column (fb-x) and row (fb-y).
; ===========================================================================

; right: 16x11, overlay, 44 bytes, offset 0, tip (7,0)
ARW_RIGHT_TYPE   = $02
ARW_RIGHT_HEIGHT = 11
ARW_RIGHT_OFFSET = 0
ARW_RIGHT_TX     = 7
ARW_RIGHT_TY     = 0
; left: 16x11, overlay, 44 bytes, offset 44, tip (8,10)
ARW_LEFT_TYPE   = $02
ARW_LEFT_HEIGHT = 11
ARW_LEFT_OFFSET = 44
ARW_LEFT_TX     = 8
ARW_LEFT_TY     = 10
; up: 16x13, overlay, 52 bytes, offset 88, tip (0,6)
ARW_UP_TYPE   = $02
ARW_UP_HEIGHT = 13
ARW_UP_OFFSET = 88
ARW_UP_TX     = 0
ARW_UP_TY     = 6
; down: 16x13, overlay, 52 bytes, offset 140, tip (15,6)
ARW_DOWN_TYPE   = $02
ARW_DOWN_HEIGHT = 13
ARW_DOWN_OFFSET = 140
ARW_DOWN_TX     = 15
ARW_DOWN_TY     = 6

ARROWS_BYTES = 192

arrows_data:
        .byte   $00, $00, $03, $80, $01, $00, $06, $C0, $03, $80, $0C, $60, $07, $C0, $18, $30
        .byte   $0C, $60, $33, $98, $18, $30, $67, $CC, $30, $18, $4F, $E4, $30, $18, $4F, $E4
        .byte   $3F, $F8, $40, $04, $1F, $F0, $60, $0C, $00, $00, $3F, $F8, $00, $00, $1F, $FC
        .byte   $0F, $F8, $30, $06, $1F, $FC, $20, $02, $18, $0C, $27, $F2, $18, $0C, $27, $F2
        .byte   $0C, $18, $33, $E6, $06, $30, $19, $CC, $03, $E0, $0C, $18, $01, $C0, $06, $30
        .byte   $00, $80, $03, $60, $00, $00, $01, $C0, $00, $00, $07, $C0, $03, $80, $0C, $60
        .byte   $07, $C0, $18, $20, $0C, $C0, $33, $20, $18, $C0, $67, $20, $30, $C0, $CF, $20
        .byte   $70, $C0, $8F, $20, $30, $C0, $CF, $20, $18, $C0, $67, $20, $0C, $C0, $33, $20
        .byte   $07, $C0, $18, $20, $03, $80, $0C, $60, $00, $00, $07, $C0, $00, $00, $03, $E0
        .byte   $01, $C0, $06, $30, $03, $E0, $04, $18, $03, $30, $04, $CC, $03, $18, $04, $E6
        .byte   $03, $0C, $04, $F3, $03, $0E, $04, $F1, $03, $0C, $04, $F3, $03, $18, $04, $E6
        .byte   $03, $30, $04, $CC, $03, $E0, $04, $18, $01, $C0, $06, $30, $00, $00, $03, $E0
