; ===========================================================================
; flames - GENERATED by tools/sprgen.py --batch. Do not edit.
; ===========================================================================
; 27 sprites packed into one 168-byte blob.
; All NO-overlay (pure white/transparent), width padded to 8px where
; the source (or its --tate rotation) came out narrower.
; ===========================================================================

; flame_l_up1 - from assets/png/flame_large_up1.png: 16x4, type $12, 8 bytes, offset 0
FLAME_L_UP1_TYPE   = $12
FLAME_L_UP1_HEIGHT = 4
FLAME_L_UP1_OFFSET = 0
; flame_l_up2 - from assets/png/flame_large_up2.png: 16x4, type $12, 8 bytes, offset 8
FLAME_L_UP2_TYPE   = $12
FLAME_L_UP2_HEIGHT = 4
FLAME_L_UP2_OFFSET = 8
; flame_l_up3 - from assets/png/flame_large_up3.png: 16x4, type $12, 8 bytes, offset 16
FLAME_L_UP3_TYPE   = $12
FLAME_L_UP3_HEIGHT = 4
FLAME_L_UP3_OFFSET = 16
; flame_l_dn1 - from assets/png/flame_large_dn1.png: 16x4, type $12, 8 bytes, offset 24
FLAME_L_DN1_TYPE   = $12
FLAME_L_DN1_HEIGHT = 4
FLAME_L_DN1_OFFSET = 24
; flame_l_dn2 - from assets/png/flame_large_dn2.png: 16x4, type $12, 8 bytes, offset 32
FLAME_L_DN2_TYPE   = $12
FLAME_L_DN2_HEIGHT = 4
FLAME_L_DN2_OFFSET = 32
; flame_l_dn3 - from assets/png/flame_large_dn3.png: 16x4, type $12, 8 bytes, offset 40
FLAME_L_DN3_TYPE   = $12
FLAME_L_DN3_HEIGHT = 4
FLAME_L_DN3_OFFSET = 40
; flame_m_up1 - from assets/png/flame_med_up1.png: 16x3, type $12, 6 bytes, offset 48
FLAME_M_UP1_TYPE   = $12
FLAME_M_UP1_HEIGHT = 3
FLAME_M_UP1_OFFSET = 48
; flame_m_up2 - from assets/png/flame_med_up2.png: 16x3, type $12, 6 bytes, offset 54
FLAME_M_UP2_TYPE   = $12
FLAME_M_UP2_HEIGHT = 3
FLAME_M_UP2_OFFSET = 54
; flame_m_up3 - from assets/png/flame_med_up3.png: 16x3, type $12, 6 bytes, offset 60
FLAME_M_UP3_TYPE   = $12
FLAME_M_UP3_HEIGHT = 3
FLAME_M_UP3_OFFSET = 60
; flame_m_dn1 - from assets/png/flame_med_dn1.png: 16x3, type $12, 6 bytes, offset 66
FLAME_M_DN1_TYPE   = $12
FLAME_M_DN1_HEIGHT = 3
FLAME_M_DN1_OFFSET = 66
; flame_m_dn2 - from assets/png/flame_med_dn2.png: 16x3, type $12, 6 bytes, offset 72
FLAME_M_DN2_TYPE   = $12
FLAME_M_DN2_HEIGHT = 3
FLAME_M_DN2_OFFSET = 72
; flame_m_dn3 - from assets/png/flame_med_dn3.png: 16x3, type $12, 6 bytes, offset 78
FLAME_M_DN3_TYPE   = $12
FLAME_M_DN3_HEIGHT = 3
FLAME_M_DN3_OFFSET = 78
; flame_s_up1 - from assets/png/flame_small_up1.png: 8x2, type $11, 2 bytes, offset 84
FLAME_S_UP1_TYPE   = $11
FLAME_S_UP1_HEIGHT = 2
FLAME_S_UP1_OFFSET = 84
; flame_s_up2 - from assets/png/flame_small_up2.png: 8x2, type $11, 2 bytes, offset 86
FLAME_S_UP2_TYPE   = $11
FLAME_S_UP2_HEIGHT = 2
FLAME_S_UP2_OFFSET = 86
; flame_s_up3 - from assets/png/flame_small_up3.png: 8x2, type $11, 2 bytes, offset 88
FLAME_S_UP3_TYPE   = $11
FLAME_S_UP3_HEIGHT = 2
FLAME_S_UP3_OFFSET = 88
; flame_s_up4 - from assets/png/flame_small_up4.png: 8x2, type $11, 2 bytes, offset 90
FLAME_S_UP4_TYPE   = $11
FLAME_S_UP4_HEIGHT = 2
FLAME_S_UP4_OFFSET = 90
; flame_s_dn1 - from assets/png/flame_small_dn1.png: 8x2, type $11, 2 bytes, offset 92
FLAME_S_DN1_TYPE   = $11
FLAME_S_DN1_HEIGHT = 2
FLAME_S_DN1_OFFSET = 92
; flame_s_dn2 - from assets/png/flame_small_dn2.png: 8x2, type $11, 2 bytes, offset 94
FLAME_S_DN2_TYPE   = $11
FLAME_S_DN2_HEIGHT = 2
FLAME_S_DN2_OFFSET = 94
; flame_s_dn3 - from assets/png/flame_small_dn3.png: 8x2, type $11, 2 bytes, offset 96
FLAME_S_DN3_TYPE   = $11
FLAME_S_DN3_HEIGHT = 2
FLAME_S_DN3_OFFSET = 96
; flame_s_dn4 - from assets/png/flame_small_dn4.png: 8x2, type $11, 2 bytes, offset 98
FLAME_S_DN4_TYPE   = $11
FLAME_S_DN4_HEIGHT = 2
FLAME_S_DN4_OFFSET = 98
; flame_xl_dn1 - from assets/png/flame_xl_dn1.png: 32x5, type $14, 20 bytes, offset 100
FLAME_XL_DN1_TYPE   = $14
FLAME_XL_DN1_HEIGHT = 5
FLAME_XL_DN1_OFFSET = 100
; flame_xl_dn2 - from assets/png/flame_xl_dn2.png: 32x5, type $14, 20 bytes, offset 120
FLAME_XL_DN2_TYPE   = $14
FLAME_XL_DN2_HEIGHT = 5
FLAME_XL_DN2_OFFSET = 120
; flame_xl_dn3 - from assets/png/flame_xl_dn3.png: 32x5, type $14, 20 bytes, offset 140
FLAME_XL_DN3_TYPE   = $14
FLAME_XL_DN3_HEIGHT = 5
FLAME_XL_DN3_OFFSET = 140
; flame_xs_up1 - from assets/png/flame_xs_up1.png: 8x2, type $11, 2 bytes, offset 160
FLAME_XS_UP1_TYPE   = $11
FLAME_XS_UP1_HEIGHT = 2
FLAME_XS_UP1_OFFSET = 160
; flame_xs_up2 - from assets/png/flame_xs_up2.png: 8x2, type $11, 2 bytes, offset 162
FLAME_XS_UP2_TYPE   = $11
FLAME_XS_UP2_HEIGHT = 2
FLAME_XS_UP2_OFFSET = 162
; flame_xs_dn1 - from assets/png/flame_xs_dn1.png: 8x2, type $11, 2 bytes, offset 164
FLAME_XS_DN1_TYPE   = $11
FLAME_XS_DN1_HEIGHT = 2
FLAME_XS_DN1_OFFSET = 164
; flame_xs_dn2 - from assets/png/flame_xs_dn2.png: 8x2, type $11, 2 bytes, offset 166
FLAME_XS_DN2_TYPE   = $11
FLAME_XS_DN2_HEIGHT = 2
FLAME_XS_DN2_OFFSET = 166

flames_BYTES = 168

flames_data:
        .byte   $00, $3E, $13, $6F, $65, $BF, $00, $1A, $00, $6A, $32, $F7, $85, $AF, $00, $36
        .byte   $00, $2C, $C5, $D7, $1A, $BB, $00, $56, $7C, $00, $F6, $C8, $FD, $A6, $58, $00
        .byte   $56, $00, $EF, $4C, $F5, $A1, $6C, $00, $34, $00, $EB, $A3, $DD, $58, $6A, $00
        .byte   $02, $6F, $05, $FB, $00, $DE, $00, $DE, $0D, $F7, $02, $6F, $00, $6F, $01, $BD
        .byte   $00, $DF, $F6, $40, $DF, $A0, $7B, $00, $7B, $00, $EF, $B0, $F6, $40, $F6, $00
        .byte   $BD, $80, $FB, $00, $25, $0B, $0B, $45, $05, $8B, $0B, $17, $A4, $D0, $D0, $A2
        .byte   $A0, $D1, $D0, $E8, $07, $80, $00, $00, $0D, $EF, $D8, $00, $0F, $FF, $EE, $60
        .byte   $07, $7D, $80, $00, $07, $C0, $00, $00, $07, $40, $00, $00, $0F, $EF, $C0, $00
        .byte   $0F, $FC, $EC, $D0, $0D, $FF, $B0, $00, $07, $80, $00, $00, $07, $C0, $00, $00
        .byte   $07, $77, $80, $00, $0F, $FF, $F6, $40, $0D, $FE, $D8, $00, $07, $C0, $00, $00
        .byte   $03, $0A, $1A, $03, $C0, $50, $58, $C0
