; =============================================================================
; music.s - the song, and the switch that takes it out again
; =============================================================================
; PLACEHOLDER, AND IT IS ON. There is no campaign music yet; the song is the
; title-theme sketch (efs_title_theme_sketch_rearranged10.vgm, see the Makefile),
; started at power-on so the intro and title have sound, and stopped by FIRE on
; the title (screens.s). With MUSIC_ON = 0 every byte below assembles to nothing
; and its two banks go with it.
;
; The Makefile strips the .vgm as a prerequisite whether or not the switch is
; on, so the file has to be in the repository for a clone to build.
;
; WHY A SILENT CARTRIDGE COULD NOT ANSWER THIS. design_technical.md 11.19 lets
; the object pool live in the RAM under the cartridge window, read inside
; brackets that clear CART_EN. The OS's VGM player is the one thing in the
; machine that re-banks that window FROM THE IRQ - `vgm_tick` fires at VSYNC,
; wherever the game happens to be, including in the middle of a bracket. It
; saves CART_SHADOW, maps the song's bank, reads, and restores the whole saved
; byte (cpu_os.s), so it SHOULD hand a bracket back its cleared CART_EN rather
; than a set one. Until a song plays, that "should" is all there is, and it is
; the prerequisite open_questions.md F5 names. With MUSIC_ON = 1 the bench fires
; vgm_tick mid-frame on purpose (tools/preview.py), at a different point in every
; frame: 216 of 220 landed inside a bracket, every one restored the cleared
; CART_EN, and the trace came back identical to the silent build. The answer
; stopped being a reading of somebody else's source. Turn the switch back on to
; reproduce it.
;
; HOW THE STREAM IS STORED. vgm_play does no header parsing: it starts executing
; commands at the address it is given and loops on the stream's own $66. So the
; cartridge stores the COMMAND STREAM only - tools/vgmstrip.py removes the VGM
; header and the GD3 tag, and emits the loop anchor as an assembler constant
; beside it. The stream is bank-aligned at $8000 of MUSIC_BANK and runs
; contiguously from there; the OS's cursor crosses banks by itself.
;
; This costs NO RAM. The stream is never copied anywhere - it is read out of the
; window by the player, a few bytes a frame, which is the one access pattern
; cart.cfg's COLD note calls the natural tenant of a bank.
; =============================================================================

MUSIC_ON    = 1                 ; 0 = no song, no banks, no player calls
MUSIC_BANK  = 8                 ; the stream's first bank. Banks 0-6 are the
                                ;   code, the tables, COLD and the screens'
                                ;   pictures, and bank 7 is MSGDATA - see
                                ;   cart.cfg
MUSIC_BANKS = 2                 ; ...and how many it takes. TEMPORARY: the song
                                ;   is the title-theme sketch
                                ;   (efs_title_theme_sketch_rearranged10.vgm,
                                ;   12,863 B stripped - see the Makefile), played
                                ;   from power-on and stopped when a game starts
                                ;   (screens.s). The blob is padded to exactly this
                                ;   below rather than the linker filling the
                                ;   area, which is what lets MUSIC_ON = 0 emit
                                ;   NO banks at all instead of four empty ones.
                                ;   A song too big for them makes the .res
                                ;   negative, and that is an assembly error
                                ;   naming this line - not a silent truncation

.if MUSIC_ON
        .include "../assets/vgm/title_stream.inc"    ; TITLE_MUSIC_HAS_LOOP /
                                                     ;   TITLE_MUSIC_LOOP_OFF,
                                                     ;   generated by vgmstrip.py
.endif

        ; Declared unconditionally: cart.cfg names this segment, and a config
        ; that names one nothing fills is a linker warning on every silent
        ; build. Empty, it contributes no bytes - the area does not fill.
        .segment "MUSICBLOB"
.if MUSIC_ON
music_blob:
        .incbin "../assets/vgm/title_stream.bin"
        .res    (MUSIC_BANKS * $2000) - (* - music_blob), $00
.endif

        .segment "HIDATA"

; -----------------------------------------------------------------------------
; music_start - arm and start the song. Called once, from cart_init.
; -----------------------------------------------------------------------------
; The stream begins at $8000 of MUSIC_BANK. The loop anchor is a BYTE OFFSET
; into that stream, so it becomes bank + off/$2000 and $8000 + off mod $2000 -
; the 8 KB window's arithmetic, done at assembly time.
;
; Nothing here touches the window itself: vgm_play only records where the song
; is. The player does the banking from the IRQ, on its own, from the next frame
; on - which is exactly the thing being measured.
; -----------------------------------------------------------------------------
        .pushseg                        ; UICODE, not HIDATA: it runs once, from
        .segment "UICODE"               ;   cart_init, and bank 3 (HIDATA +
                                        ;   CODE3) has no room for its bytes
music_start:
.if MUSIC_ON
        lda     #MUSIC_BANK
        sta     OS_ARG+0
        stz     OS_ARG+1                ; ...at $8000 of it
        lda     #$80
        sta     OS_ARG+2
.if TITLE_MUSIC_HAS_LOOP
        lda     #(MUSIC_BANK + (TITLE_MUSIC_LOOP_OFF / $2000))
        sta     OS_ARG+3
        lda     #<($8000 + (TITLE_MUSIC_LOOP_OFF .MOD $2000))
        sta     OS_ARG+4
        lda     #>($8000 + (TITLE_MUSIC_LOOP_OFF .MOD $2000))
        sta     OS_ARG+5
        jmp     API_VGM_PLAY_LOOP       ; loop past the one-shot intro
.else
        jmp     API_VGM_PLAY            ; no anchor - loop the whole stream
.endif
.else
        rts
.endif
        .popseg
