; ===========================================================================
; pickups_art - GENERATED by tools/pickupgen.py from assets/png/
; bonusbox1.png .. bonusbox4.png. Do not edit.
; ===========================================================================
; The pickup: 4 frames, in the hardware's own axes (NOT --tate).
; Every pickup, whatever it holds, looks like this.
; ===========================================================================

; bonusbox1: 16x16, overlay, 64 bytes, offset 0
; bonusbox2: 16x16, overlay, 64 bytes, offset 64
; bonusbox3: 16x16, overlay, 64 bytes, offset 128
; bonusbox4: 16x16, overlay, 64 bytes, offset 192
PK_TYPE     = $02
PK_W        = 16             ; full-res px, along fb-x
PK_HEIGHT   = 16             ; ...and rows, along fb-y
PK_FRAMES   = 4             ; the animation, one sprite slot each
PK_BYTES    = 64             ; ...frame n at n * this from PK_PAGE
PK_PAGES    = 1             ; GPU pages, from PK_PAGE on

pickups_data:
        .byte   $00, $00, $7F, $FE, $3F, $FC, $40, $02, $20, $04, $5F, $FA, $20, $04, $5F, $FA
        .byte   $20, $04, $5F, $FA, $20, $04, $5F, $FA, $20, $04, $5F, $FA, $20, $04, $5F, $FA
        .byte   $20, $04, $5F, $FA, $20, $04, $5F, $FA, $20, $04, $5F, $FA, $20, $04, $5F, $FA
        .byte   $20, $04, $5F, $FA, $3F, $FC, $40, $02, $00, $00, $7F, $FE, $00, $00, $00, $00
        .byte   $00, $00, $3F, $FC, $1F, $F8, $20, $04, $10, $08, $2F, $F4, $10, $08, $2F, $F4
        .byte   $20, $04, $5F, $FA, $20, $04, $5F, $FA, $20, $04, $5F, $FA, $40, $02, $BF, $FD
        .byte   $40, $02, $BF, $FD, $40, $02, $BF, $FD, $7F, $FE, $80, $01, $40, $02, $BF, $FD
        .byte   $20, $04, $5F, $FA, $20, $04, $5F, $FA, $1F, $F8, $20, $04, $00, $00, $3F, $FC
        .byte   $1F, $F8, $20, $04, $10, $08, $2F, $F4, $30, $0C, $4F, $F2, $20, $04, $5F, $FA
        .byte   $20, $04, $5F, $FA, $40, $02, $BF, $FD, $40, $02, $BF, $FD, $7F, $FE, $80, $01
        .byte   $40, $02, $BF, $FD, $40, $02, $BF, $FD, $20, $04, $5F, $FA, $20, $04, $5F, $FA
        .byte   $30, $0C, $4F, $F2, $10, $08, $2F, $F4, $1F, $F8, $20, $04, $00, $00, $3F, $FC
        .byte   $00, $00, $3F, $FC, $1F, $F8, $20, $04, $20, $04, $5F, $FA, $20, $04, $5F, $FA
        .byte   $40, $02, $BF, $FD, $7F, $FE, $80, $01, $40, $02, $BF, $FD, $40, $02, $BF, $FD
        .byte   $40, $02, $BF, $FD, $20, $04, $5F, $FA, $20, $04, $5F, $FA, $20, $04, $5F, $FA
        .byte   $10, $08, $2F, $F4, $10, $08, $2F, $F4, $1F, $F8, $20, $04, $00, $00, $3F, $FC
