; =============================================================================
; speech.s - the voice: the phoneme strings, and the bank they are read from
; =============================================================================
; The CPU OS can speak (API_SPK_SAY, $FFEA): three square waves tracing the
; first three formants of an utterance plus the noise voice for the bursts, 60 Hz
; parameter frames, no PCM and no samples. This file is the cartridge's half of
; it - the phoneme strings for the messages that are spoken, and nothing else.
; The engine, the phoneme table and the glides are firmware (MAD-65 roms/cpu_os.s,
; and carts/speech_test is where it was proved).
;
; WHAT IS SPOKEN AND WHY ONLY THAT. Speech reduced this far is RECOGNISABLE, not
; decodable cold, so the voice only ever rides on a line the message bar is
; already showing. That is the condition the prototype was accepted on, and it is
; why the table is indexed by the IM_* id: a spoken message is a displayed
; message with phonemes attached, never an announcement of its own.
;
; THE VOICE IS ON THE MUSIC PSG. SN76489 #1, the chip the song plays on - not the
; effects chip. Nothing is left of the effects PSG's four voices during a fight
; (sfx.s pins the gun, the rock hits, the ship's hits and the noise), while the
; song is 3125 YM2413 writes to 17 PSG #1 writes and stops at the start of a game
; (screens.s). So speech takes three tone voices and the noise voice of a chip
; that is silent in flight, and the effects keep every voice they have. When there
; IS game music, its PSG tracks duck for the length of the utterance - SPK_BUSY is
; the flag to duck on.
;
; IT LIVES IN THE MESSAGE BANK. SPKDATA is a second segment in bank MSG_BANK,
; beside MSGDATA (cart.cfg), and the whole of it is read through the SAME
; msg_open / msg_close bracket the text is read through:
;
;   * spk_say COPIES the string into the OS's own 63-phoneme buffer and the tick
;     then reads only RAM, so the pointer has to be valid FOR ONE CALL - which is
;     exactly what a window already open on the message bank gives it. There is no
;     second bracket and no spk_open;
;   * SPK_LO/SPK_HI are read INSIDE that bracket - unlike IND_LO/IND_HI, which
;     hud_game.s keeps in RODATA and reads before it. That is not symmetry for its
;     own sake: upper RAM ($A000-$BEFF) has 16 bytes left after CODE7, and 28
;     bytes of pointer table would not fit. In the bank they cost nothing;
;   * one bank keeps the pointers flat 16-bit, which is the reason bank 9 exists
;     at all (cart.cfg, THE MESSAGE BANK). 118 bytes of phonemes and 28 of pointers
;     against ~7.7 KB free: the spoken half will not be what fills it.
; =============================================================================

        .segment "SPKDATA"

        .include "speech.inc"           ; GENERATED by tools/mkspeech.py, which is
                                        ;   where an utterance is written - the
                                        ;   phoneme strings and SPK_LO/SPK_HI

        ; The pointer table is indexed by the IM_* id and has to have one entry
        ; per id. IM_COUNT is hud_game.s's count of them, so a message added there
        ; without a row here (silent or not) fails the build instead of speaking
        ; whatever byte follows the table.
        .assert SPK_IDS = IM_COUNT, error, "speech.s: tools/mkspeech.py's MESSAGES no longer has one entry per IM_* id - see hud_game.s"
        .assert (SPK_HI - SPK_LO) = IM_COUNT, error, "speech.s: SPK_LO is not IM_COUNT bytes long"

; --- the voice's settings, and the one call that uses them --------------------
; VOICE_, not SPK_: the OS's own internal state carries the SPK_ names ($024E is
; its copy of the chip, $0251 of the scale) and these four are the cartridge's
; arguments, written into OS_ARG at the call and nowhere else.
VOICE_CHIP  = 0                 ; SN76489 #1, the MUSIC PSG - see the header
VOICE_TEMPO = 0                 ; the engine's own pace
VOICE_VOL   = 0                 ; full: a warning is not background
VOICE_SCALE = $FE               ; -2, the longest vocal tract the engine has and
                                ;   so its lowest voice. The ship's computer is
                                ;   not a person and should not sound like one

        .pushseg
        .segment "CODE4"                ; the run area behind laser.s, which has
                                        ;   ~340 bytes free. NOT CODE2, where
                                        ;   hud_game.s's caller lives: that one is
                                        ;   a bank and has ~40 left, and the three
                                        ;   bytes of the jsr are all it can spare

; -----------------------------------------------------------------------------
; spk_speak - say the message that is now on the bar, if it has a voice at all.
; -----------------------------------------------------------------------------
; CALLED FROM ind_next (hud_game.s) INSIDE ITS msg_open BRACKET, after ind_build
; has laid the text into IND_BUF - so the window is showing the message bank, the
; text is on its way to the screen this same phase, and the voice and the words
; start together. That is the whole arrangement; there is no timer anywhere.
;
; IT TAKES THE ID FROM IND_CUR, not from X. ind_build ran in between and X is
; its column cursor by the end of it - and ind_next itself has already put the
; id where both halves can find it. (The reverted first attempt at this feature
; passed the id in X across a jsr and that was one of its two real bugs.)
;
; A $0000 POINTER MEANS SILENT, and most messages are: the table has one entry
; per IM_* id and tools/mkspeech.py fills in only the ones that speak.
;
; IT DOES NOT ASK WHETHER SOMETHING IS ALREADY SPEAKING. spk_say replaces the
; utterance, and the bar cannot advance to a new line while one is being read out
; (ind_timer_tick holds it on SPK_BUSY) - so the only way here mid-sentence is
; indicate_urgent, the queue-jumper, whose three messages are all silent today.
; A silent line therefore changes the WORDS while the voice finishes the sentence
; behind it, which is the wanted behaviour: never cut speech off mid-word.
; -----------------------------------------------------------------------------
spk_speak:
        ldx     IND_CUR                 ; the id, from RAM - not from X
        cpx     #IM_COUNT               ; IQ_NONE, or anything else that is not an
        bcs     @silent                 ;   id, reads no table
        lda     SPK_LO,x                ; the table is IN THE BANK, read here
        sta     OS_ARG+4                ;   because here the bank is open
        lda     SPK_HI,x
        sta     OS_ARG+5
        ora     OS_ARG+4                ; $0000 -> this message is not spoken
        beq     @silent
        lda     #VOICE_CHIP
        sta     OS_ARG+0
        lda     #VOICE_TEMPO
        sta     OS_ARG+1
        lda     #VOICE_VOL
        sta     OS_ARG+2
        lda     #VOICE_SCALE
        sta     OS_ARG+3
        jmp     API_SPK_SAY             ; tail. It copies the string out of the
                                        ;   window before it returns
@silent:
        rts

        .popseg
